[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 13.0

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
# For Mac
option_as_alt = "OnlyLeft"
opacity = 0.85
